#!/bin/bash
# Quick Start - Deploy em Render + Vercel

echo "🚀 DEPLOY RÁPIDO - LUMEN ERP PRODUÇÃO"
echo "====================================="
echo ""

echo "✅ PRÉ-REQUISITOS VERIFICADOS:"
echo "  ✓ Backend builds com sucesso"
echo "  ✓ Frontend builds com sucesso (Next.js)"
echo "  ✓ Testes passam (253 testes)"
echo "  ✓ Sem secrets hardcoded"
echo "  ✓ Rate limiting implementado"
echo "  ✓ Security headers configurados"
echo ""

echo "📋 PASSO 1: SUPABASE PRODUÇÃO"
echo "-----------------------------"
echo ""
echo "1. Ir para https://app.supabase.com"
echo "2. Criar novo projeto (separado do dev)"
echo "3. No SQL Editor, rodar scripts/01-bootstrap-roles.sql"
echo "4. Copiar valores:"
echo "   - DATABASE_URL (role app_api)"
echo "   - DIRECT_URL (role prisma_migrator)"
echo "   - SUPABASE_SECRET_KEY (em Settings → API)"
echo ""

echo "📋 PASSO 2: DEPLOY BACKEND (RENDER)"
echo "-----------------------------------"
echo ""
echo "1. Ir para https://dashboard.render.com"
echo "2. New → Web Service"
echo "3. Conectar seu repositório GitHub"
echo ""
echo "4. Configurar:"
echo "   Name: lumen-erp-api"
echo "   Root Directory: (deixar vazio)"
echo "   Dockerfile: docker/Dockerfile.api"
echo "   Branch: main"
echo ""
echo "5. Environment Variables (ver .env.production.template):"
echo "   DATABASE_URL"
echo "   DIRECT_URL"
echo "   SUPABASE_URL"
echo "   SUPABASE_JWKS_URL"
echo "   SUPABASE_PUBLISHABLE_KEY"
echo "   SUPABASE_SECRET_KEY (marcar como Secret)"
echo "   CORS_ORIGINS=https://lumenerp.vercel.app"
echo "   NODE_ENV=production"
echo ""
echo "6. Health Check:"
echo "   Path: /api/v1/health"
echo "   Interval: 30s"
echo ""
echo "7. Clicar em Deploy"
echo "   ⏱ Aguardar 5-10 minutos"
echo ""
echo "8. Após deploy, ir para Shell:"
echo "   pnpm --filter @erp/api exec prisma migrate deploy"
echo "   pnpm --filter @erp/api exec prisma db seed"
echo ""

echo "📋 PASSO 3: DEPLOY FRONTEND (VERCEL)"
echo "------------------------------------"
echo ""
echo "1. Ir para https://vercel.com/new"
echo "2. Conectar seu repositório GitHub"
echo ""
echo "3. Configurar:"
echo "   Framework: Next.js"
echo "   Root Directory: apps/web"
echo "   Build Command: pnpm install && pnpm --filter @erp/web build"
echo ""
echo "4. Environment Variables:"
echo "   NEXT_PUBLIC_SUPABASE_URL=https://xxxxx.supabase.co"
echo "   NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=eyJ..."
echo "   NEXT_PUBLIC_API_URL=https://lumen-erp.onrender.com/api/v1"
echo ""
echo "5. Deploy"
echo "   ⏱ Aguardar 3-5 minutos"
echo ""

echo "📋 PASSO 4: VERIFICAÇÃO"
echo "----------------------"
echo ""
echo "Teste no navegador:"
echo ""
echo "1. Backend health:"
echo "   curl https://lumen-erp.onrender.com/api/v1/health"
echo "   → Deve retornar: {\"status\":\"ok\"}"
echo ""
echo "2. Frontend:"
echo "   Abrir: https://lumenerp.vercel.app"
echo "   → Deve abrir página de login"
echo ""
echo "3. Fazer login com admin"
echo ""
echo "4. Testar fluxos:"
echo "   ✓ Criar produto"
echo "   ✓ Fazer venda"
echo "   ✓ Gerar orçamento"
echo "   ✓ Baixar PDF"
echo ""

echo ""
echo "📚 DOCUMENTAÇÃO COMPLETA"
echo "----------------------"
echo ""
echo "Ver arquivos criados:"
echo "  docs/deploy.md                    - Deploy detalhado (Coolify reference)"
echo "  docs/DEPLOY-RENDER-VERCEL.md      - Guia específico Render + Vercel"
echo "  docs/SECURITY.md                  - Segurança aplicada"
echo "  .env.production.template          - Template de .env produção"
echo "  scripts/deploy-production.sh      - Checklist automatizado"
echo ""

echo "💡 DICAS IMPORTANTES"
echo "--------------------"
echo ""
echo "⚠️  CORS_ORIGINS é obrigatório em produção"
echo "    A API NÃO sobe sem definir"
echo ""
echo "⚠️  SUPABASE_SECRET_KEY deve ser Secret no Render"
echo "    Não deixar em plain text nos logs"
echo ""
echo "⚠️  Migrations rodam como comando separado"
echo "    Não rodam automaticamente no start da API"
echo ""
echo "⚠️  Swagger desligado em produção"
echo "    NODE_ENV=production faz isso automaticamente"
echo ""

echo ""
echo "🔗 LINKS ÚTEIS"
echo "--------------"
echo ""
echo "Render:   https://dashboard.render.com"
echo "Vercel:   https://vercel.com"
echo "Supabase: https://app.supabase.com"
echo "GitHub:   seu-repo"
echo ""

echo "✨ Qualquer dúvida, ver docs/DEPLOY-RENDER-VERCEL.md"
